from __future__ import annotations

import asyncio
import json
import logging
import tempfile
import unittest
from pathlib import Path

from ev.commands import direct_action
from ev.events import PhaxEventBus
from ev.network import NetworkDiagnostics, resolver_observation, route_observation, tailscale_observation
from ev.planner import TaskPlanner
from ev.state import StateMachine
from ev.tools import ToolContext, ToolRegistry
from ev.tools.network import register_network_tools
from ev.tools.results import evaluate_result


def reply(data, code=0):
    return {'code': code, 'out': json.dumps(data), 'err': ''}


class NetworkFileTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.path = Path(self.temporary.name) / 'resolv.conf'

    def test_generator_is_evidence_not_ownership_or_success(self):
        self.path.write_text('# Generated by NetworkManager\nnameserver 127.0.0.53\nnameserver 127.0.0.53\n')
        before = self.path.read_bytes()
        data = resolver_observation(self.path)
        self.assertEqual(data['generator'], 'NetworkManager')
        self.assertEqual(data['nameservers'], ['127.0.0.53'])
        self.assertFalse(data['ownership_verified'])
        self.assertFalse(data['lookup_verified'])
        self.assertEqual(self.path.read_bytes(), before)

    def test_manual_ipv6_configuration_does_not_invent_an_owner(self):
        self.path.write_text('nameserver 2001:db8::53\nsearch private.example\n')
        data = resolver_observation(self.path)
        self.assertEqual(data['generator'], 'UNKNOWN')
        self.assertEqual(data['nameservers'], ['2001:db8::53'])
        self.assertNotIn('private.example', json.dumps(data))

    def test_conflicting_markers_remain_unknown(self):
        self.path.write_text('# Generated by NetworkManager\n# Generated by resolvconf\nnameserver 1.1.1.1\n')
        self.assertEqual(resolver_observation(self.path)['generator'], 'UNKNOWN')

    def test_bad_and_oversized_resolver_files_are_not_used(self):
        for text in ('nameserver not-an-address\n', 'x' * 65537):
            self.path.write_text(text)
            result = resolver_observation(self.path)
            self.assertEqual(result['status'], 'UNAVAILABLE')
            self.assertEqual(result['nameservers'], [])
        self.path.unlink()
        import os
        os.mkfifo(self.path)
        self.assertEqual(resolver_observation(self.path)['status'], 'UNAVAILABLE')

    def test_default_routes_keep_table_evidence_without_claiming_selection(self):
        data = route_observation(reply([{'dst':'default','gateway':'192.0.2.1','dev':'wifi0','table':52},
                                         {'dst':'192.0.2.0/24','dev':'wifi0'}]), 'IPv4')
        self.assertEqual(len(data['defaults']), 1)
        self.assertEqual(data['defaults'][0]['table'], 52)
        self.assertIn('not verified', data['scope'])
        data = route_observation(reply([{'dst':'::/0','dev':'eth0','nexthops':[{'dev':'eth1'}]}]), 'IPv6')
        self.assertTrue(data['defaults'][0]['multipath'])

    def test_failed_route_inventory_is_not_an_observed_empty_table(self):
        for data in (reply([], code=1), reply({}), reply([{'dst':'default','metric':True}])):
            self.assertEqual(route_observation(data, 'IPv4')['status'], 'UNAVAILABLE')
        self.assertEqual(route_observation(reply([]), 'IPv4')['status'], 'OBSERVED')

    def test_running_tailscale_requires_local_identity_and_address(self):
        self.assertEqual(tailscale_observation(reply({'BackendState':'Running'}))['status'], 'UNAVAILABLE')
        data = tailscale_observation(reply({'BackendState':'Running', 'Self':{'ID':'owned','TailscaleIPs':['100.64.0.1']}}))
        self.assertEqual(data['daemon_state'], 'Running')
        self.assertFalse(data['reachability_verified'])
        self.assertEqual(tailscale_observation(reply({'BackendState':'Stopped'}))['daemon_state'], 'Stopped')


class NetworkFlowTests(unittest.IsolatedAsyncioTestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.path = Path(self.temporary.name) / 'resolv.conf'
        self.path.write_text('')
        self.calls = []

    async def mobile(self):
        return False

    async def runner(self, argv, **limits):
        self.calls.append((argv, limits))
        if argv[0] == 'tailscale':
            return reply({'BackendState':'Stopped'})
        return reply([])

    def observer(self, runner=None):
        return NetworkDiagnostics(runner or self.runner, self.path,
                                  interfaces=lambda:{'status':'OBSERVED','items':[{'name':'lo','up':True,'kind':'LOOPBACK'}]},
                                  mobile=self.mobile)

    async def test_local_diagnosis_reports_missing_evidence_and_never_repairs(self):
        result = await self.observer().observe()
        self.assertIn('No default route', result['message'])
        self.assertIn('no nameservers', result['message'])
        self.assertIn('No non-loopback', result['message'])
        self.assertIn('Tailscale is not', result['message'])
        self.assertEqual(result['internet'], {'status':'UNKNOWN','probe_attempted':False})
        self.assertFalse(result['settings_changed'])
        self.assertEqual(len(self.calls), 3)
        self.assertTrue(all(0 < limits['timeout'] <= 2 and limits['maximum'] <= 1048576 for _, limits in self.calls))
        self.assertEqual(self.path.read_text(), '')

    async def test_failed_inventory_does_not_diagnose_absent_routes(self):
        async def runner(argv, **limits):
            return reply([], code=1)
        result = await self.observer(runner).observe()
        self.assertEqual(result['status'], 'PARTIAL')
        self.assertNotIn('No default route', result['message'])
        self.assertIn('inventory is unavailable', result['message'])

    async def test_cancellation_waits_for_all_native_probe_cleanup(self):
        started = asyncio.Event()
        active = 0
        cleaned = []
        async def runner(argv, **limits):
            nonlocal active
            active += 1
            if active == 3:
                started.set()
            try:
                await asyncio.Event().wait()
            finally:
                await asyncio.sleep(.01)
                cleaned.append(argv)
        task = asyncio.create_task(self.observer(runner).observe())
        await asyncio.wait_for(started.wait(), 1)
        task.cancel()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertEqual(len(cleaned), 3)

    async def test_repeated_cancellation_does_not_interrupt_probe_cleanup(self):
        started, cleaning, release = asyncio.Event(), asyncio.Event(), asyncio.Event()
        active = 0
        cleaned = []
        async def runner(argv, **limits):
            nonlocal active
            active += 1
            if active == 3:
                started.set()
            try:
                await asyncio.Event().wait()
            finally:
                cleaning.set()
                await release.wait()
                cleaned.append(argv)
        task = asyncio.create_task(self.observer(runner).observe())
        await asyncio.wait_for(started.wait(), 1)
        task.cancel()
        await asyncio.wait_for(cleaning.wait(), 1)
        task.cancel()
        await asyncio.sleep(.01)
        self.assertFalse(task.done())
        release.set()
        with self.assertRaises(asyncio.CancelledError):
            await task
        self.assertEqual(len(cleaned), 3)

    async def test_explicit_read_commands_plan_locally_and_dry_run_sends_nothing(self):
        bus = PhaxEventBus()
        registry = ToolRegistry(ToolContext({}, bus, logging.getLogger('test')))
        register_network_tools(registry)
        spec = registry.get('system.diagnose_network')
        self.assertTrue(spec.read_only)
        self.assertEqual(spec.public()['contract_gaps'], [])
        self.assertEqual(evaluate_result(spec.name, {'status':'PARTIAL'}).scope, 'observation_only')
        calls = []
        async def requester(payload, _request_id):
            calls.append(payload)
            return {'status':'completed', 'result':await self.observer().observe()}
        planner = TaskPlanner(registry, requester, bus, StateMachine(bus))
        for text in ('diagnose my network', 'show network diagnostics', "why can't I look anything up?", 'Why cannot I connect to the internet?'):
            self.assertEqual(direct_action(text).tool, spec.name)
            plan = planner.try_plan(text, 'network')
            self.assertIsNotNone(plan, text)
            result = await planner.execute(plan)
            self.assertEqual(result['status'], 'completed')
            self.assertIn('unknown', result['response'])
        before = len(calls)
        plan = planner.try_plan('dry run, diagnose my network', 'preview')
        self.assertTrue(plan.dry_run)
        await planner.execute(plan)
        self.assertEqual(len(calls), before)

    def test_explanations_negations_and_repairs_are_not_passive_diagnoses(self):
        for text in ('explain why I cannot connect to the internet', 'do not diagnose my network',
                     'if I say diagnose my network', 'change my DNS', 'why can\'t I look anything up and reset my network?',
                     'the button says diagnose my network'):
            self.assertIsNone(direct_action(text), text)


if __name__ == '__main__':
    unittest.main()
