"""Local network evidence. No repair commands or Internet probes."""

from __future__ import annotations

import asyncio
import ipaddress
import json
import os
import stat
from pathlib import Path

import psutil

from .process_runner import command, settle
from .remote_health import mobile_ready


def resolver_observation(path: Path) -> dict:
    result = {"status": "UNAVAILABLE", "path": str(path), "generator": "UNKNOWN",
              "generator_evidence": "No known symlink or generator marker",
              "ownership_verified": False, "nameservers": []}
    try:
        target = path.resolve(strict=True)
        result["resolved_path"] = str(target)
        fd = os.open(target, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
        try:
            info = os.fstat(fd)
            if not stat.S_ISREG(info.st_mode) or info.st_size > 65536:
                raise ValueError("Resolver configuration is not a bounded regular file")
            data = os.read(fd, 65537)
            if len(data) > 65536:
                raise ValueError("Resolver configuration exceeds its limit")
            text = data.decode("utf-8", errors="strict")
        finally:
            os.close(fd)
        candidates = set()
        known_paths = {"systemd-resolved": ("/run/systemd/resolve/",),
                       "NetworkManager": ("/run/NetworkManager/",),
                       "resolvconf": ("/run/resolvconf/", "/var/run/resolvconf/")}
        for name, prefixes in known_paths.items():
            if any(str(target).startswith(prefix) for prefix in prefixes):
                candidates.add(name)
        for line in text.splitlines():
            stripped = line.strip()
            if stripped.startswith("#"):
                lower = stripped.casefold()
                if "generated by networkmanager" in lower:
                    candidates.add("NetworkManager")
                if "generated by resolvconf" in lower:
                    candidates.add("resolvconf")
                if "generated by dhcpcd" in lower:
                    candidates.add("dhcpcd")
            fields = stripped.split()
            if fields and fields[0] == "nameserver":
                if len(fields) != 2:
                    raise ValueError("Malformed resolver address")
                address = str(ipaddress.ip_address(fields[1]))
                if address not in result["nameservers"]:
                    result["nameservers"].append(address)
        if len(candidates) == 1:
            result["generator"] = candidates.pop()
            result["generator_evidence"] = "Observed symlink target or generator comment; current ownership is not proven"
        elif candidates:
            result["generator_evidence"] = "Conflicting generator evidence; ownership is unknown"
        result["status"] = "OBSERVED"
        result["lookup_verified"] = False
        result["scope"] = "resolv.conf only; application DNS-over-HTTPS, split DNS and NSS may differ"
    except (OSError, ValueError, UnicodeError):
        result["error"] = "Resolver configuration unavailable, malformed or exceeds its limit"
        result["nameservers"] = []
    return result


def interface_observation(sysnet: Path = Path('/sys/class/net')) -> dict:
    try:
        addresses = psutil.net_if_addrs()
        stats = psutil.net_if_stats()
        if len(stats) > 256:
            raise ValueError("Too many interfaces")
        items = []
        for name, current in stats.items():
            if not isinstance(name, str) or len(name) > 64 or "/" in name or name in {".", ".."}:
                raise ValueError("Invalid interface name")
            kind = "Wi-Fi" if (sysnet / name / "wireless").is_dir() else "UNKNOWN"
            try:
                if (sysnet / name / "type").read_text().strip() == "772":
                    kind = "LOOPBACK"
                elif kind == "UNKNOWN" and (sysnet / name / "device").exists() and (sysnet / name / "type").read_text().strip() == "1":
                    kind = "WIRED_OR_ETHERNET_DRIVER"
            except OSError:
                pass
            ips = [a.address for a in addresses.get(name, [])
                   if a.family.name in {"AF_INET", "AF_INET6"}]
            items.append({"name": name, "up": current.isup, "kind": kind,
                          "addresses": ips[:32], "speed_mbps": current.speed})
        return {"status": "OBSERVED", "items": items}
    except (OSError, ValueError, psutil.Error):
        return {"status": "UNAVAILABLE", "items": []}


def route_observation(reply: dict, family: str) -> dict:
    result = {"family": family, "status": "UNAVAILABLE", "defaults": []}
    try:
        if reply.get("code") != 0:
            raise ValueError("Route inventory failed")
        rows = json.loads(reply["out"])
        if not isinstance(rows, list) or len(rows) > 4096:
            raise ValueError("Route inventory malformed or too large")
        for row in rows:
            if not isinstance(row, dict):
                raise ValueError("Malformed route")
            if row.get("dst") not in {"default", "0.0.0.0/0", "::/0"}:
                continue
            route = {}
            for key in ("dev", "gateway", "table", "metric", "type", "protocol", "scope"):
                value = row.get(key)
                if value is None:
                    continue
                if isinstance(value, bool) or not isinstance(value, (str, int)) or len(str(value)) > 128:
                    raise ValueError("Malformed route identity")
                route[key] = value
            hops = row.get("nexthops", [])
            if not isinstance(hops, list) or len(hops) > 64:
                raise ValueError("Malformed multipath route")
            if hops:
                route["multipath"] = True
            result["defaults"].append(route)
            if len(result["defaults"]) > 64:
                raise ValueError("Too many default routes")
        result["status"] = "OBSERVED"
        result["scope"] = "All routing tables; policy selection and gateway reachability are not verified"
    except (ValueError, TypeError, KeyError):
        result["defaults"] = []
    return result


def tailscale_observation(reply: dict) -> dict:
    result = {"status": "UNAVAILABLE", "reachability_verified": False}
    try:
        if reply.get("code") != 0:
            raise ValueError("Daemon inventory failed")
        data = json.loads(reply["out"])
        if not isinstance(data, dict) or not isinstance(data.get("BackendState"), str):
            raise ValueError("Missing daemon state")
        if data['BackendState'] == 'Running':
            node = data.get('Self')
            if not isinstance(node, dict) or not isinstance(node.get('ID'), str) or not node['ID']:
                raise ValueError("Missing local node identity")
            addresses = node.get('TailscaleIPs')
            if not isinstance(addresses, list) or not 1 <= len(addresses) <= 16:
                raise ValueError("Missing node addresses")
            for address in addresses:
                ipaddress.ip_address(address)
            result['local_addresses'] = addresses
        result.update(status="OBSERVED", daemon_state=data["BackendState"],
                      scope="Local daemon state; peer or public mobile access is not verified")
    except (ValueError, TypeError, KeyError):
        pass
    return result


class NetworkDiagnostics:
    def __init__(self, runner=command, resolver=Path('/etc/resolv.conf'),
                 interfaces=interface_observation, mobile=mobile_ready):
        self.run, self.resolver, self.interfaces, self.mobile = runner, resolver, interfaces, mobile

    async def observe(self):
        probes = (
            self.run(['ip', '-j', '-4', 'route', 'show', 'table', 'all'], timeout=2, maximum=262144),
            self.run(['ip', '-j', '-6', 'route', 'show', 'table', 'all'], timeout=2, maximum=262144),
            self.run(['tailscale', 'status', '--json'], timeout=2, maximum=1048576),
            asyncio.to_thread(resolver_observation, self.resolver),
            asyncio.to_thread(self.interfaces), self.mobile(),
        )
        tasks = [asyncio.create_task(probe) for probe in probes]
        group = asyncio.gather(*tasks, return_exceptions=True)
        try:
            results = await asyncio.shield(group)
            for result in results:
                if isinstance(result, BaseException):
                    raise result
        except BaseException:
            for task in tasks:
                if not task.done() and not task.cancelling():
                    task.cancel()
            await settle(group)
            raise
        routes = [route_observation(results[0], 'IPv4'), route_observation(results[1], 'IPv6')]
        dns, links = results[3], results[4]
        tailscale = tailscale_observation(results[2])
        findings = []
        if any(r['status'] != 'OBSERVED' for r in routes):
            findings.append("Part of the route inventory is unavailable; a missing observation does not mean there is no route.")
        if all(r['status'] == 'OBSERVED' for r in routes) and not any(r['defaults'] for r in routes):
            findings.append("No default route was observed in either address family. Policy routing and reachability still need checking.")
        if dns['status'] == 'OBSERVED' and not dns['nameservers']:
            findings.append("resolv.conf has no nameservers. Other DNS mechanisms may still be configured.")
        if dns['status'] != 'OBSERVED':
            findings.append("Resolver configuration could not be read safely; its DNS settings are unknown.")
        if links['status'] == 'OBSERVED' and not any(i['up'] and i['kind'] != 'LOOPBACK' for i in links['items']):
            findings.append("No non-loopback link is reported up.")
        if tailscale['status'] == 'OBSERVED' and tailscale['daemon_state'] != 'Running':
            findings.append("Tailscale is not in its Running state; this may affect private mobile access.")
        findings.append("No DNS lookup or Internet connection was attempted; Internet reachability is unknown.")
        return {'status': 'OBSERVED' if any(r['status'] == 'OBSERVED' for r in routes) else 'PARTIAL',
                'routes': routes, 'dns': dns, 'interfaces': links,
                'tailscale': tailscale,
                'mobile_backend': {'loopback_health_observed': results[5], 'public_access_verified': False},
                'internet': {'status': 'UNKNOWN', 'probe_attempted': False},
                'findings': findings, 'message': ' '.join(findings), 'settings_changed': False}
